#!/usr/bin/python
#GPLv2

import png
import os
import sys
import json

def pr(*l):
  print(" ".join(map(str, l)))

with file('settings.json') as fin:
  settings = json.load(fin)
  dpm = float(settings['inputDPI'])/25.4
  spotsize = float(settings['spotSize'])
  machinedpm = float(settings['machineDPI'])/25.4
  basic_speed = float(settings['basicSpeed'])
  oversampling = float(settings['oversampling'])
  focus_speed = float(settings['focusSpeed'])
  travel_speed = float(settings['travelSpeed'])
  focusedZ = float(settings['focusedZ'])
  travelZ = float(settings['travelZ'])
  endZ = float(settings['endZ'])


def get_pixel(i, x, y, meta):
  x *= meta['planes']
  w = meta['size'][0]
  l = i[y]
  #print>>sys.stderr, '\n',x
  return l[x]

def get_rect(img, x, y, size, meta):
  r = []
  for i in xrange(x-size, x+size):
    for j in xrange(y-size, y+size):
      r.append(get_pixel(img, x, y, meta))
  return r

def get_rect_avg(img, x, y, size, meta):
  s = 0.0
  count = 0
  #print>>sys.stderr, x,y
  for i in xrange(x-size, x+size):
    for j in xrange(y-size, y+size):
      s += get_pixel(img, x, y, meta)
      count += 1
  return s / count

def get_average(pixels):
  return float(sum(pixels))/len(pixels)

def main():
  # header
  pr('G90') # absolute pos
  pr('G21') # units in mm
  pr('G28') # go home
  pr('G01 Z{} F9000'.format(travelZ)) # go to standby position

  w, h, img, meta = png.Reader(filename=sys.argv[1]).asDirect()
  img = list(img)
  wdpm, hdpm = w/dpm, h/dpm
  linescount = hdpm / spotsize
  rowscount = wdpm / spotsize
  spot_in_img = spotsize * dpm

  pen_is_up = True
  alt = False
  _cnt = 0
  _speed = basic_speed * oversampling # 170 is basic speed, 3 is oversampling
  #l_x, l_y = (0,0)
  for lnum in xrange(int((linescount-1)*oversampling)):
    lnum /= float(oversampling)
    rows = xrange(int((rowscount-1)*oversampling))
    rows = reversed(rows) if alt else rows
    alt = not alt
    _cnt += 1
    if _cnt > 10:
      print>>sys.stderr, lnum, 'of', linescount, '   \r',
      _cnt = 0
    for rnum in rows:
       rnum /= float(oversampling)
       avg = get_rect_avg(img, int(spot_in_img*rnum+spot_in_img),
                          int(spot_in_img*lnum+spot_in_img),
                          int(spot_in_img), meta)
       _x, _y = lnum*spot_in_img/dpm, rnum*spot_in_img/dpm
       if avg < 250:
         if pen_is_up:
           pr('G01 X{} Y{} Z{} F{}'.format(_x, _y, travelZ, travel_speed))
           pen_is_up = False

           pr('G01 X{} Y{} Z{} F{}'.format(_x, _y, focusedZ, focus_speed))
           #l_x, l_y = (_x, _y)
       else:
         if not pen_is_up:
           pr('G01 X{} Y{} Z{} F{}'.format(_x, _y, focusedZ, _speed))
           pr('G01 X{} Y{} Z{} F{}'.format(_x, _y, travelZ, focus_speed))
           pen_is_up = True

  # footer
  pr('G01 Z{} F9000'.format(endZ))

if __name__ == "__main__":
  main()
