#!/usr/bin/python
#GPLv2

import cv2
import sys

def pr(*l):
  print(" ".join(map(str, l)))

with file('settings.json') as fin:
  import json
  settings = json.load(fin)
  dpm = float(settings['inputDPI'])/25.4
  spotsize = float(settings['spotSize'])
  machinedpm = float(settings['machineDPI'])/25.4
  basic_speed = float(settings['basicSpeed'])
  oversampling = float(settings['oversampling'])
  focus_speed = float(settings['focusSpeed'])
  travel_speed = float(settings['travelSpeed'])
  focusedZ = float(settings['focusedZ'])
  travelZ = float(settings['travelZ'])
  endZ = float(settings['endZ'])
  passes = int(settings['passes'])

def main():
  # header
  pr('G90') # absolute pos
  pr('G21') # units in mm
  pr('G28') # go home
  pr('G01 Z{} F9000'.format(travelZ)) # go to standby position

  img = cv2.imread(sys.argv[1], 0)
#  imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

  contours, hierarchy = cv2.findContours(img, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
  #print hierarchy
  for contour in contours:
    pr('G5 L1')
    for p in contour:
      p = p[0]
      #print p
      pr('G01 X{} Y{} Z{} F{}'.format(p[0]/dpm, p[1]/dpm, focusedZ, basic_speed))
    if len(contour) > 0:
      p = contour[0][0]
      pr('G01 X{} Y{} Z{} F{}'.format(p[0]/dpm, p[1]/dpm, focusedZ, basic_speed))

    pr('G5 L0')
  pr('G01 Z{} F9000'.format(endZ))

if __name__ == "__main__":
  main()
